# Generated by Django 4.1 on 2022-12-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('star_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='about-video')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='banners')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CommentHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('image', models.FileField(upload_to='home-comment-images')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('video', models.FileField(upload_to='home-comment-works')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='star_all.star')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('image', models.FileField(upload_to='banners')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='star_all.star')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
        migrations.CreateModel(
            name='ExampleHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example', to='star_all.star')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_example', to='star_all.starwork')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='star_all.star')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
    ]
