# Generated by Django 4.1 on 2022-12-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('star_all', '0002_starcomment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='banners')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('image', models.FileField(upload_to='banners')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='star_all.star')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
    ]
