# Generated by Django 4.1 on 2022-12-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_all', '0003_remove_starcomment_grade_starcomment_rating_and_more'),
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('image', models.FileField(upload_to='home-comment-images')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
        migrations.CreateModel(
            name='ExampleHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example', to='star_all.star')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_example', to='star_all.starwork')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='star_all.star')),
            ],
            options={
                'ordering': ['custom_id'],
            },
        ),
    ]
