# Generated by Django 4.1 on 2022-12-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='star-images')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('deadline', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='StarCategory',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StarWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='star_works')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_works', to='star_all.star')),
            ],
        ),
        migrations.CreateModel(
            name='StarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='comment_images')),
                ('grade', models.FloatField()),
                ('created_at', models.DateField(auto_now=True)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_comments', to='star_all.star')),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stars', to='star_all.starcategory'),
        ),
    ]
