# Generated by Django 4.1 on 2022-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starcomment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
