# Generated by Django 4.1 on 2022-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_all', '0002_starcomment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starcomment',
            name='grade',
        ),
        migrations.AddField(
            model_name='starcomment',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='starcomment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
