# Generated by Django 4.1 on 2023-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_all', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
