# Generated by Django 4.1 on 2022-12-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_all', '0004_toast_toastcategory_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='toast',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_all.toastcategory'),
        ),
    ]
